name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t frontend:latest ./frontend
          docker build -t backend:latest ./backend
          docker build -t orders:latest ./orders
          docker build -t nginx:latest ./nginx

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start backend
        run: |
          docker compose up -d backend1
          sleep 5  
          
      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/api/products; then
              break
            fi
            echo "Waiting for backend..."
            sleep 3
          done

      - name: Install dependencies and run tests
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
          pytest tests/test_api.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build

